/**
 * Renders the seed as SQL for a real Supabase project. Settings: only hours,
 * commission and pickup ETA are written — the WhatsApp number and
 * `accepting_orders` stay as the owner set them (closed by default).
 */
import type { MenuData } from '@/lib/types';

const q = (s: string) => `'${s.replace(/'/g, "''")}'`;
const j = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

export function renderSeedSql(seed: MenuData): string {
  const categories = seed.categories
    .map((c) => `  (${q(c.id)}, ${q(c.slug)}, ${j(c.name)}, ${c.sort_order}, ${c.active})`)
    .join(',\n');
  const items = seed.items
    .map((i) =>
      `  (${q(i.id)}, ${q(i.category_id)}, ${q(i.slug)}, ${j(i.name)}, ${i.description ? j(i.description) : 'null'}, ${i.price}, ${i.image_path ? q(i.image_path) : 'null'}, ${j(i.options)}, ${i.is_sold_out}, ${i.active}, ${i.sort_order})`)
    .join(',\n');
  const zones = seed.zones
    .map((z) => `  (${q(z.id)}, ${q(z.slug)}, ${j(z.name)}, ${z.fee}, ${z.eta_minutes}, ${z.min_order}, ${z.active}, ${z.sort_order})`)
    .join(',\n');

  return `-- Generated by \`npm run db:seed-sql\` from src/lib/data/seed.ts. Do not edit by hand.
-- JAMRA is a fictional brand: menu, prices and zones are invented demo data.
begin;

insert into public.categories (id, slug, name, sort_order, active) values
${categories}
on conflict (id) do update set slug = excluded.slug, name = excluded.name,
  sort_order = excluded.sort_order, active = excluded.active;

insert into public.menu_items (id, category_id, slug, name, description, price, image_path, options, is_sold_out, active, sort_order) values
${items}
on conflict (id) do update set category_id = excluded.category_id, slug = excluded.slug, name = excluded.name,
  description = excluded.description, price = excluded.price, image_path = excluded.image_path,
  options = excluded.options, is_sold_out = excluded.is_sold_out, active = excluded.active,
  sort_order = excluded.sort_order;

insert into public.delivery_zones (id, slug, name, fee, eta_minutes, min_order, active, sort_order) values
${zones}
on conflict (id) do update set slug = excluded.slug, name = excluded.name, fee = excluded.fee,
  eta_minutes = excluded.eta_minutes, min_order = excluded.min_order, active = excluded.active,
  sort_order = excluded.sort_order;

update public.settings set
  opening_hours = ${j(seed.settings.opening_hours)},
  commission_rate = ${seed.settings.commission_rate},
  pickup_eta_minutes = ${seed.settings.pickup_eta_minutes}
where id;

commit;
`;
}
